name: nahornyi-ailab-landing
services:
- name: web
  type: static_site
  source_dir: /
  github:
    repo: YOUR_GITHUB_USERNAME/nahornyi-ailab-landing
    branch: main
  build_command: npm run build
  output_dir: /out
  routes:
  - path: /
  environment_slug: node-js
  run_command: npm start
  
domains:
- domain: nahornyi.ai
  type: PRIMARY
- domain: www.nahornyi.ai
  type: ALIAS
