export const copy = {
  nav: {
    services: "Services",
    cases: "Cases", 
    value: "Value",
    contact: "Contact"
  },
  hero: {
    title: 'We create AI that works for your business',
    subtitle: 'We implement advanced AI solutions that optimize processes, reduce costs and accelerate growth.',
    slogan: 'AI won\'t take over the world unless we help it.',
    primary_cta: 'Discuss your project',
    secondary_cta: 'Book a call',
  },
  services: {
    title: "Services",
    items: [
      {title: "Custom ML Models", desc: "Train your own models on private servers. Sensitive data handling with full security isolation."},
      {title: "AI/ML Infrastructure", desc: "Dedicated GPU servers, model deployment, MLOps pipelines, monitoring & scaling."},
      {title: "Data Science & Engineering", desc: "ETL for ML, feature engineering, model validation, A/B testing for AI features."},
      {title: "n8n Automation", desc: "Integrations, pipelines, alerts, ETL, production hardening."},
      {title: "LLM Agents", desc: "RAG, vector DBs, prompt engineering, MCP, fine-tuning."},
      {title: "Chatbots", desc: "Telegram/WhatsApp/Viber — leadgen, support, payments."},
      {title: "QA Autotests", desc: "E2E/UI, case generation, regression, screenshots & reports."},
      {title: "BI & Analytics", desc: "Data collection, dashboards, messenger alerts."},
      {title: "Consulting & Architecture", desc: "Audits, solution design, MVP launch."}
    ]
  },
  value: {
    title: "What money we make",
    lead: "We measure value in revenue gained, hours saved, and downtime avoided.",
    bullets: [
      {title: "Leads & sales", desc: "+15–40% conversion via bots and funnels."},
      {title: "Operational savings", desc: "−20–60 hours/week of routine (≈ −1–3 FTE)."},
      {title: "Release speed", desc: "−50–80% regression time with autotests."},
      {title: "SLA & incidents", desc: "−30–70% reaction time; less downtime (TG/WA alerts)."},
      {title: "Retention", desc: "+5–12% repeat purchases with personalization."}
    ]
  },
  roi: {
    title: "ROI calculator",
    cta: "Calculate ROI",
    fields: [
      {id: "leadsPerMonth", label: "Leads per month"},
      {id: "avgConversionUplift", label: "Conversion uplift, %"},
      {id: "avgCheck", label: "Average order value, €"},
      {id: "hoursSavedPerWeek", label: "Hours saved/week"},
      {id: "hourlyCost", label: "Hourly cost, €"}
    ],
    formulaDesc: "Revenue = Leads × Uplift% × AOV; Savings = Hours × Rate × 4.3. ROI = (Revenue+Savings−Cost)/Cost"
  },
  cases: {
    title: "Cases",
    items: [
      {title: "n8n error alerts → Telegram/WhatsApp", desc: "Multilingual template + guides. Incident response time slashed."},
      {title: "Autogenerated QA test cases", desc: "From BRD to cases, export to Sheets/TestRail. Dozens of hours saved."}
    ]
  },
  contact: {
    title: "Contact",
    form: {
      name: "Name",
      email: "Email or Telegram @",
      message: "What do you need to automate?"
    },
    submit: "Send",
    thanks: "Thanks! We'll get back to you shortly."
  },
  footer: {
    rights: "© Nahornyi AILab, Valencia",
    description: "AI automation for Valencia and beyond. Fast, pragmatic, ROI-first.",
    sections: {
      contact: "Contact",
      services: "Services",
      location: "Location",
      bot: "Bot"
    },
    whatsapp: "WhatsApp",
    services_list: {
      n8n: "n8n Automation",
      chatbots: "Chatbots",
      qa: "QA Autotests",
      llm: "LLM Agents"
    },
    location_info: {
      city: "Valencia",
      remote: "Global Remote"
    },
    made_with: "Made with Claude Code"
  },
  header: {
    contact_button: "Contact"
  },
  hero_hardcoded: {
    subtitle_mobile: "AI solutions",
    subtitle_desktop: "AI solutions — not reports.",
    cta_primary: "Discuss your use case", 
    cta_secondary: "What we build"
  },
  roi_results: {
    monthly_revenue: "Monthly Revenue",
    monthly_savings: "Monthly Savings", 
    roi: "ROI",
    total_monthly_benefit: "Total Monthly Benefit",
    sending: "Sending..."
  },
  contact_messages: {
    response_time: "We typically respond within 24 hours."
  },
  achievements: {
    title: "Our Achievements"
  },
  worksProjects: {
    title: "Our Works & Projects",
    ariaLabel: "Our works and projects",
    buttons: {
      view: "View",
      openInTelegram: "Open in Telegram"
    },
    types: {
      app: "Mobile App",
      platform: "Web Platform",
      telegram_bot: "Telegram Bot", 
      web_app: "Web Application",
      automation: "Automation Project"
    },
    items: [
      {
        title: "Traduktor",
        description: "AI-powered voice translator supporting 30+ languages. Real-time speech recognition and neural translation."
      },
      {
        title: "n8n Automation",
        description: "Powerful workflow automation platform for integrations, pipelines, and business process automation."
      },
      {
        title: "Valencia Info Bot", 
        description: "Telegram bot with useful information about Valencia. Helps newcomers and city residents find the information they need."
      }
    ]
  }
  
} as const;