export const copy = {
  nav: {
    services: "Services",
    cases: "Cases", 
    value: "Value",
    contact: "Contact"
  },
  hero: {
    h1: "AI automation that drives revenue — not reports.",
    sub: "n8n, chatbots (Telegram/WhatsApp/Viber), integrations, QA autotests, LLM agents. Fast. Pragmatic. ROI-first.",
    cta_primary: "Discuss your use case",
    cta_secondary: "What we build"
  },
  services: {
    title: "Services",
    items: [
      {title: "n8n Automation", desc: "Integrations, pipelines, alerts, ETL, production hardening."},
      {title: "Chatbots", desc: "Telegram/WhatsApp/Viber — leadgen, support, payments."},
      {title: "QA Autotests", desc: "E2E/UI, case generation, regression, screenshots & reports."},
      {title: "LLM Agents", desc: "RAG, vector DBs, prompt engineering, MCP."},
      {title: "BI & Analytics", desc: "Data collection, dashboards, messenger alerts."},
      {title: "Consulting & Architecture", desc: "Audits, solution design, MVP launch."}
    ]
  },
  value: {
    title: "What money we make",
    lead: "We measure value in revenue gained, hours saved, and downtime avoided.",
    bullets: [
      {title: "Leads & sales", desc: "+15–40% conversion via bots and funnels."},
      {title: "Operational savings", desc: "−20–60 hours/week of routine (≈ −1–3 FTE)."},
      {title: "Release speed", desc: "−50–80% regression time with autotests."},
      {title: "SLA & incidents", desc: "−30–70% reaction time; less downtime (TG/WA alerts)."},
      {title: "Retention", desc: "+5–12% repeat purchases with personalization."}
    ]
  },
  roi: {
    title: "ROI calculator",
    cta: "Calculate ROI",
    fields: [
      {id: "leadsPerMonth", label: "Leads per month"},
      {id: "avgConversionUplift", label: "Conversion uplift, %"},
      {id: "avgCheck", label: "Average order value, €"},
      {id: "hoursSavedPerWeek", label: "Hours saved/week"},
      {id: "hourlyCost", label: "Hourly cost, €"}
    ],
    formulaDesc: "Revenue = Leads × Uplift% × AOV; Savings = Hours × Rate × 4.3. ROI = (Revenue+Savings−Cost)/Cost"
  },
  cases: {
    title: "Cases",
    items: [
      {title: "n8n error alerts → Telegram/WhatsApp", desc: "Multilingual template + guides. Incident response time slashed."},
      {title: "Autogenerated QA test cases", desc: "From BRD to cases, export to Sheets/TestRail. Dozens of hours saved."}
    ]
  },
  contact: {
    title: "Contact",
    form: {
      name: "Name",
      email: "Email or Telegram @",
      message: "What do you need to automate?"
    },
    submit: "Send",
    thanks: "Thanks! We'll get back to you shortly."
  },
  footer: {
    rights: "© Nahornyi AILab, Valencia",
    description: "AI automation for Valencia and beyond. Fast, pragmatic, ROI-first.",
    sections: {
      contact: "Contact",
      services: "Services",
      location: "Location",
      bot: "Bot"
    },
    whatsapp: "WhatsApp",
    services_list: {
      n8n: "n8n Automation",
      chatbots: "Chatbots",
      qa: "QA Autotests",
      llm: "LLM Agents"
    },
    location_info: {
      city: "Valencia",
      remote: "Global Remote"
    },
    made_with: "Made with Claude Code"
  },
  header: {
    contact_button: "Contact"
  },
  hero_hardcoded: {
    subtitle_mobile: "AI automation that drives revenue",
    subtitle_desktop: "AI automation that drives revenue — not reports.",
    cta_primary: "Discuss your use case", 
    cta_secondary: "What we build"
  },
  roi_results: {
    monthly_revenue: "Monthly Revenue",
    monthly_savings: "Monthly Savings", 
    roi: "ROI",
    total_monthly_benefit: "Total Monthly Benefit",
    sending: "Sending..."
  },
  contact_messages: {
    response_time: "We typically respond within 24 hours."
  }
} as const;